name: Docker Build Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: App
      APP_PORT: 3000
      API_PORT: 5200

    steps:
      - uses: actions/checkout@v4

      - name: Create env file for main application
        run:
          touch app/.env
          echo "# Keep it empty for now" > app/.env
          cat app/.env
          printf "\n\n"

      - name: Build with docker compose
        run: |
          echo "Begin image build"
          docker compose --profile release build

      - name: Run with docker compose
        run: |
          echo "Running containers on Production mode"
          docker compose --profile release up -d
          sleep 10
          docker compose logs app-release
          docker compose logs api-service-release
          docker compose --profile release down
          echo "done"