name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run with docker compose
      run:
        docker compose build
        docker compose up --abort-on-container-exit --exit-code-from app
